spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  data:
    mongodb:
      database: web-genius
      uri: mongodb+srv://<mongodb_user>:<mongo_dbpassword>@<mongodb_rui>


application:
  client-origin-url: http://localhost:3000/

server:
  error:
    whitelabel:
      enabled: false
  port: 8080
