spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  data:
    mongodb:
      database: web-genius
      uri: mongodb+srv://emmanueljonathant453:BLQZOTm2MOTZUM1n@grounddata.qepd9bf.mongodb.net/


application:
  client-origin-url: http://localhost:3000/

server:
  error:
    whitelabel:
      enabled: false
  port: 8080